### PR TITLE
check for empty kubeletArgument

### LINKED ISSUE #1278: logging-fluentd pods fail to start after upgrading from 3.7 to 3.9
Hello Origin folks,

We have used the origin-ansible scripts to upgrade our 3.7 Origin cluster to 3.9 and it has completed successfully, but our fluentd pods are failing to start with the following error:

```
-e:2:in `<main>': undefined method `[]' for nil:NilClass (NoMethodError)
```
All of the logging-fluentd pods repeat this behavior until they stop with crash loop back off. 

We have tried adding some extra debug statements to the logging-fluentd Config Map but it has not provided us with any additional information. 

```
[bens@osndev1 ~]$ openshift version
openshift v3.9.0+ba7faec-1
kubernetes v1.9.1+a0ce1bc657
etcd 3.2.16
[bens@osndev1 ~]$ oc version
oc v3.9.0+ba7faec-1
kubernetes v1.9.1+a0ce1bc657
features: Basic-Auth GSSAPI Kerberos SPNEGO
```
We have tried manually deleting the pods so that they refresh themselves, as well as completely deleting the logging project and re-running the config.yml playbook to rebuild the logging with the same result.

I am attaching the output of the origin-aggregated-logging dump script to this issue. Please let me know if there's additional information I can provide. Thank you.
[logging-dump.tar.gz](https://github.com/openshift/origin-aggregated-logging/files/2274639/logging-dump.tar.gz)

### PR DESCRIPTION
**Pull request by jcantrill**
Fix https://bugzilla.redhat.com/show_bug.cgi?id=1614528

fix #1278

### CODE REVIEW

**Comment by jcantrill** [comment]
@richm backport to 3.9 and 3.10?
