### ISSUE TITLE
logging-fluentd pods fail to start after upgrading from 3.7 to 3.9

### ISSUE THREAD

**Issue by benscottub** [openshift/origin-aggregated-logging#1278]
Hello Origin folks,

We have used the origin-ansible scripts to upgrade our 3.7 Origin cluster to 3.9 and it has completed successfully, but our fluentd pods are failing to start with the following error:

```
-e:2:in `<main>': undefined method `[]' for nil:NilClass (NoMethodError)
```
All of the logging-fluentd pods repeat this behavior until they stop with crash loop back off. 

We have tried adding some extra debug statements to the logging-fluentd Config Map but it has not provided us with any additional information. 

```
[bens@osndev1 ~]$ openshift version
openshift v3.9.0+ba7faec-1
kubernetes v1.9.1+a0ce1bc657
etcd 3.2.16
[bens@osndev1 ~]$ oc version
oc v3.9.0+ba7faec-1
kubernetes v1.9.1+a0ce1bc657
features: Basic-Auth GSSAPI Kerberos SPNEGO
```
We have tried manually deleting the pods so that they refresh themselves, as well as completely deleting the logging project and re-running the config.yml playbook to rebuild the logging with the same result.

I am attaching the output of the origin-aggregated-logging dump script to this issue. Please let me know if there's additional information I can provide. Thank you.
[logging-dump.tar.gz](https://github.com/openshift/origin-aggregated-logging/files/2274639/logging-dump.tar.gz)

**Comment by richm** [comment]
Try this:

oc edit configmap/logging-fluentd - change this:
```
@include configs.d/openshift/system.conf
```
to this
```
<system>
  log_level debug
</system>
```
Then `oc set env ds/logging-fluentd VERBOSE=true DEBUG=true` - this should trigger a redeployment of fluentd, and fluentd will write a log file to /var/log/fluentd.log on its local node.  That file will hopefully contain more information.

**Comment by benscottub** [comment]
Hey Rich, thank you for the fast response. Here is the verbose output from the redeployment:

[logging-fluentd-6jcng.log](https://github.com/openshift/origin-aggregated-logging/files/2275117/logging-fluentd-6jcng.log)

the error at the end now reads:
_=/usr/bin/env
+ echo '>>>>>>>>>>>>><<<<<<<<<<<<<<<<'
+ export USE_CRIO=false
+ USE_CRIO=false
+ node_config=/etc/origin/node/node-config.yaml
+ [[ -f /etc/origin/node/node-config.yaml ]]
>>>>>>>>>>>>><<<<<<<<<<<<<<<<
++ ruby -e 'require '\''yaml'\''; y=YAML.load_file('\''/etc/origin/node/node-config.yaml'\'')
        puts y['\''kubeletArguments'\'']['\''container-runtime-endpoint'\'']'
-e:2:in `<main>': undefined method `[]' for nil:NilClass (NoMethodError)
+ cre=

**Comment by richm** [comment]
What is in `/etc/origin/node/node-config.yaml`?  Is there a field `kubeletArguments` there?  What is the value?

**Comment by benscottub** [comment]
Here is the node-config.yaml file (grabbed from one of the nodes that is running the fluentd pods). the kubeletArguments field is blank, but our production environment nodes (which are on 3.7) also have this field blank. Should we be manually setting some variables in the kubeletArguments field?

```
proxyArguments:
  proxy-mode:
  - iptables
masterClientConnectionOverrides:
  qps: 20
  contentType: application/vnd.kubernetes.protobuf
  acceptContentTypes: application/vnd.kubernetes.protobuf,application/json
  burst: 40
volumeConfig:
  localQuota:
    perFSGroup:
dockerConfig:
  execHandlerName: ''
volumeDirectory: /var/lib/origin/openshift.local.volumes
dnsIP: XXXXXXXXXXXXXX
kubeletArguments:
networkPluginName: redhat/openshift-ovs-multitenant
kind: NodeConfig
nodeName: osndev1.acsu.buffalo.edu
dnsDomain: cluster.local
servingInfo:
  bindAddress: 0.0.0.0:10250
  keyFile: server.key
  certFile: server.crt
  clientCA: ca.crt
networkConfig:
  mtu: 1350
  networkPluginName: redhat/openshift-ovs-multitenant
apiVersion: v1
allowDisabledDocker: false
masterKubeConfig: system:node:osndev1.acsu.buffalo.edu.kubeconfig
dnsBindAddress: 127.0.0.1:53
podManifestConfig:
iptablesSyncPeriod: 5s
imageConfig:
  format: openshift/origin-${component}:${version}
  latest: false
dnsRecursiveResolvConf: /etc/origin/node/resolv.conf
```

**Comment by benscottub** [comment]
This environment started at 3.2 and we have used the openshift-ansible scripts for each upgrade. Thanks for the links - if we are hosting in our local datacenter, we would not be using the cloud-provider and cloud-config variables correct? The directory /etc/origin/cloudprovider does not exist on our nodes. I see that the node-config.yaml files you linked would be grabbing the node labels and putting them in the kubeletArguments field - would it be sufficient for us to use ```oc describe node <node_name>``` and grab the labels from that output and put that in our kubeletArguments field on each node and redeploy fluentd?

**Comment by richm** [comment]
>  would it be sufficient for us to use oc describe node <node_name> and grab the labels from that output and put that in our kubeletArguments field on each node and redeploy fluentd?

I think so, yes.

Sounds like there is/was an upgrade bug in openshift-ansible at some point, that didn't upgrade node-config.yaml.

But at any rate, fluentd shouldn't crash because of a missing field.

**Comment by benscottub** [comment]
Thanks a ton Rich, after filling out the kubeletArguments field in all of our masters and nodes our logging-fluentd pods are starting and running now.
